deployment:
  name: test-deployment
  app: busybox
  spec:
    replicas: 3
pod:
  name: hello-world-pod-again
  hostNetwork: true
  containers:
    - name: busybox
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 360000; done"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
          drop:
            - ALL
