pod:
  name: hello-world-pod-again
  hostNetwork: true
  containers:
    - name: pod-test
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 360000; done"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
          drop:
            - ALL
